### ISSUE TITLE
Making an order

### ISSUE THREAD

**Issue by allanyego** [yegow/e-booking#2]
**As an** authenticated user ,
**I want** to click 'Order'
**so that** I can make a purchase.

### Acceptance criteria
- user has to be authenticated authenticated

### Tasks
- [ ] Make button invisible to unauthenticated users
- [ ] User cart is updated

**Comment by yegow** [comment]
**As an** authenticated user,
**I can** click on the cart menu option
**so that** I can check it's items.

## Tasks
- [ ] Order button disabled for properties out of stock
